name: notework
services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    env_file:
      - /databaseEnv/.env
    volumes:
      - notework_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U notework']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
  server:
    depends_on:
      - postgres
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - /server/.env
    healthcheck:
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - 3001:3001
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - /frontend/.env
    ports:
      - 80:80
    healthcheck:
      interval: 30s
      timeout: 5s
      retries: 5
volumes:
  notework_data:
